server:
  port: 8090

spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

welcome:
  message: Welcome to daily Actual World!!

---

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

welcome:
  message: Welcome to daily Actual World!!

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

welcome:
  message: Welcome to daily Actual World!!
